name: Build & Test 

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 
        uses: actions/setup-dotnet@v4
    #    with:
     #     dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies 
        run: dotnet restore TestApl

      - name: Build 
        run: dotnet build TestApl --configuration Debug --no-restore

     # - name: Test 
      #  run: dotnet test TestApl --configuration Release --no-build